name: Ember Asset Sizes

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2-beta
      with:
        fetch-depth: 0
    - uses: NullVoxPopuli/ember-asset-size-action@upgrade-deps-and-add-yn
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
